//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 03:10:39 PM IST 
//


package com.model.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ATS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="fileVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="productVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Mappings" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Mapping" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="replaceWith" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="xpath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Channel" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Credentials">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="username" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="certificateFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="From" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="To" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="xpath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="destinationFolder" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ats",
    "mappings",
    "channel"
})
@XmlRootElement(name = "Channels")
public class Channels {

    @XmlElement(name = "ATS", required = true)
    protected Channels.ATS ats;
    @XmlElement(name = "Mappings", required = true)
    protected List<Channels.Mappings> mappings;
    @XmlElement(name = "Channel", required = true)
    protected List<Channels.Channel> channel;

    /**
     * Gets the value of the ats property.
     * 
     * @return
     *     possible object is
     *     {@link Channels.ATS }
     *     
     */
    public Channels.ATS getATS() {
        return ats;
    }

    /**
     * Sets the value of the ats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channels.ATS }
     *     
     */
    public void setATS(Channels.ATS value) {
        this.ats = value;
    }

    /**
     * Gets the value of the mappings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mappings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMappings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Channels.Mappings }
     * 
     * 
     */
    public List<Channels.Mappings> getMappings() {
        if (mappings == null) {
            mappings = new ArrayList<Channels.Mappings>();
        }
        return this.mappings;
    }

    /**
     * Gets the value of the channel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Channels.Channel }
     * 
     * 
     */
    public List<Channels.Channel> getChannel() {
        if (channel == null) {
            channel = new ArrayList<Channels.Channel>();
        }
        return this.channel;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fileVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="productVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ATS {

        @XmlAttribute(name = "fileVersion", required = true)
        protected String fileVersion;
        @XmlAttribute(name = "productVersion", required = true)
        protected String productVersion;

        /**
         * Gets the value of the fileVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileVersion() {
            return fileVersion;
        }

        /**
         * Sets the value of the fileVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileVersion(String value) {
            this.fileVersion = value;
        }

        /**
         * Gets the value of the productVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductVersion() {
            return productVersion;
        }

        /**
         * Sets the value of the productVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductVersion(String value) {
            this.productVersion = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Credentials">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="username" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="certificateFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="From" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="To" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="xpath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="destinationFolder" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "credentials",
        "from",
        "to"
    })
    public static class Channel {

        @XmlElement(name = "Credentials", required = true)
        protected Channels.Channel.Credentials credentials;
        @XmlElement(name = "From", required = true)
        protected List<Channels.Channel.From> from;
        @XmlElement(name = "To", required = true)
        protected List<Channels.Channel.To> to;
        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the credentials property.
         * 
         * @return
         *     possible object is
         *     {@link Channels.Channel.Credentials }
         *     
         */
        public Channels.Channel.Credentials getCredentials() {
            return credentials;
        }

        /**
         * Sets the value of the credentials property.
         * 
         * @param value
         *     allowed object is
         *     {@link Channels.Channel.Credentials }
         *     
         */
        public void setCredentials(Channels.Channel.Credentials value) {
            this.credentials = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the from property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFrom().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Channels.Channel.From }
         * 
         * 
         */
        public List<Channels.Channel.From> getFrom() {
            if (from == null) {
                from = new ArrayList<Channels.Channel.From>();
            }
            return this.from;
        }

        /**
         * Gets the value of the to property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the to property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Channels.Channel.To }
         * 
         * 
         */
        public List<Channels.Channel.To> getTo() {
            if (to == null) {
                to = new ArrayList<Channels.Channel.To>();
            }
            return this.to;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="username" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="certificateFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Credentials {

            @XmlAttribute(name = "url", required = true)
            protected String url;
            @XmlAttribute(name = "username", required = true)
            protected String username;
            @XmlAttribute(name = "password", required = true)
            protected String password;
            @XmlAttribute(name = "certificateFile", required = true)
            protected String certificateFile;

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

            /**
             * Gets the value of the username property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUsername() {
                return username;
            }

            /**
             * Sets the value of the username property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUsername(String value) {
                this.username = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the certificateFile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCertificateFile() {
                return certificateFile;
            }

            /**
             * Sets the value of the certificateFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCertificateFile(String value) {
                this.certificateFile = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class From {

            @XmlAttribute(name = "path", required = true)
            protected String path;

            /**
             * Gets the value of the path property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPath() {
                return path;
            }

            /**
             * Sets the value of the path property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPath(String value) {
                this.path = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="xpath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="destinationFolder" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class To {

            @XmlAttribute(name = "xpath", required = true)
            protected String xpath;
            @XmlAttribute(name = "destinationFolder", required = true)
            protected String destinationFolder;

            /**
             * Gets the value of the xpath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXpath() {
                return xpath;
            }

            /**
             * Sets the value of the xpath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXpath(String value) {
                this.xpath = value;
            }

            /**
             * Gets the value of the destinationFolder property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDestinationFolder() {
                return destinationFolder;
            }

            /**
             * Sets the value of the destinationFolder property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDestinationFolder(String value) {
                this.destinationFolder = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Mapping" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="replaceWith" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="xpath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mapping"
    })
    public static class Mappings {

        @XmlElement(name = "Mapping", required = true)
        protected List<Channels.Mappings.Mapping> mapping;
        @XmlAttribute(name = "xpath", required = true)
        protected String xpath;
        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the mapping property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mapping property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMapping().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Channels.Mappings.Mapping }
         * 
         * 
         */
        public List<Channels.Mappings.Mapping> getMapping() {
            if (mapping == null) {
                mapping = new ArrayList<Channels.Mappings.Mapping>();
            }
            return this.mapping;
        }

        /**
         * Gets the value of the xpath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXpath() {
            return xpath;
        }

        /**
         * Sets the value of the xpath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXpath(String value) {
            this.xpath = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="replaceWith" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Mapping {

            @XmlAttribute(name = "find", required = true)
            protected String find;
            @XmlAttribute(name = "replaceWith", required = true)
            protected String replaceWith;

            /**
             * Gets the value of the find property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFind() {
                return find;
            }

            /**
             * Sets the value of the find property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFind(String value) {
                this.find = value;
            }

            /**
             * Gets the value of the replaceWith property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReplaceWith() {
                return replaceWith;
            }

            /**
             * Sets the value of the replaceWith property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReplaceWith(String value) {
                this.replaceWith = value;
            }

        }

    }

}
